import 'package:flutter/material.dart';

class PatternCategoryDefinition {
  const PatternCategoryDefinition({
    required this.id,
    required this.aliases,
    required this.icons,
  });

  final String id;
  final List<String> aliases;
  final List<IconData> icons;
}

const clusterPatternLibrary = <PatternCategoryDefinition>[
  PatternCategoryDefinition(
    id: 'food-nutrition',
    aliases: [
      'food',
      'nutrition',
      'healthy eating',
      'diet',
      'fruit',
      'vegetable',
      'grain',
      'herbs',
    ],
    icons: [
      Icons.dinner_dining_outlined,
      Icons.apple_outlined,
      Icons.eco_outlined,
      Icons.grass_outlined,
      Icons.water_drop_outlined,
      Icons.local_dining_outlined,
      Icons.egg_alt_outlined,
      Icons.local_florist_outlined,
      Icons.spa_outlined,
      Icons.favorite_border_rounded,
    ],
  ),
  PatternCategoryDefinition(
    id: 'cooking-recipes',
    aliases: [
      'cooking',
      'recipe',
      'recipes',
      'chef',
      'baking',
      'kitchen',
      'ingredients',
      'meal prep',
    ],
    icons: [
      Icons.soup_kitchen_outlined,
      Icons.restaurant_outlined,
      Icons.kitchen_outlined,
      Icons.timer_outlined,
      Icons.menu_book_outlined,
      Icons.blender_outlined,
      Icons.scale_outlined,
      Icons.room_service_outlined,
      Icons.outdoor_grill_outlined,
      Icons.bakery_dining_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'fitness',
    aliases: [
      'fitness',
      'workout',
      'exercise',
      'running',
      'gym',
      'strength',
      'activity',
      'training',
    ],
    icons: [
      Icons.fitness_center_outlined,
      Icons.directions_run_outlined,
      Icons.monitor_heart_outlined,
      Icons.timer_outlined,
      Icons.sports_gymnastics_outlined,
      Icons.self_improvement_outlined,
      Icons.emoji_events_outlined,
      Icons.directions_bike_outlined,
      Icons.hiking_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'wellness',
    aliases: [
      'wellness',
      'health',
      'meditation',
      'mindfulness',
      'sleep',
      'spa',
      'breathing',
      'self care',
    ],
    icons: [
      Icons.spa_outlined,
      Icons.self_improvement_outlined,
      Icons.bedtime_outlined,
      Icons.wb_sunny_outlined,
      Icons.nights_stay_outlined,
      Icons.water_drop_outlined,
      Icons.favorite_border_rounded,
      Icons.local_cafe_outlined,
      Icons.air_outlined,
      Icons.eco_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'movies',
    aliases: [
      'movie',
      'movies',
      'film',
      'cinema',
      'thriller',
      'director',
      'screening',
    ],
    icons: [
      Icons.movie_outlined,
      Icons.local_movies_outlined,
      Icons.theaters_outlined,
      Icons.play_circle_outline_rounded,
      Icons.camera_roll_outlined,
      Icons.videocam_outlined,
      Icons.confirmation_number_outlined,
      Icons.video_library_outlined,
      Icons.camera_alt_outlined,
      Icons.live_tv_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'tv-shows',
    aliases: [
      'tv',
      'tv show',
      'television',
      'series',
      'episode',
      'streaming',
      'sitcom',
    ],
    icons: [
      Icons.tv_outlined,
      Icons.live_tv_outlined,
      Icons.connected_tv_outlined,
      Icons.settings_remote_outlined,
      Icons.video_library_outlined,
      Icons.playlist_play_outlined,
      Icons.cast_outlined,
      Icons.subscriptions_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'anime-comics',
    aliases: [
      'anime',
      'manga',
      'comic',
      'comics',
      'graphic novel',
      'animation',
    ],
    icons: [
      Icons.auto_awesome_outlined,
      Icons.chat_bubble_outline_rounded,
      Icons.dashboard_customize_outlined,
      Icons.star_outline_rounded,
      Icons.theater_comedy_outlined,
      Icons.history_edu_outlined,
      Icons.flare_outlined,
      Icons.interests_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'books-reading',
    aliases: [
      'book',
      'books',
      'reading',
      'library',
      'novel',
      'literature',
      'essay',
      'poetry',
    ],
    icons: [
      Icons.menu_book_outlined,
      Icons.bookmark_border_rounded,
      Icons.local_library_outlined,
      Icons.auto_stories_outlined,
      Icons.article_outlined,
      Icons.subject_outlined,
      Icons.edit_outlined,
      Icons.history_edu_outlined,
      Icons.library_books_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'writing',
    aliases: [
      'writing',
      'writer',
      'journal',
      'journaling',
      'copywriting',
      'notes',
      'notebook',
      'typewriter',
    ],
    icons: [
      Icons.edit_outlined,
      Icons.draw_outlined,
      Icons.description_outlined,
      Icons.notes_outlined,
      Icons.format_quote_outlined,
      Icons.history_edu_outlined,
      Icons.type_specimen_outlined,
      Icons.text_fields_outlined,
      Icons.article_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'programming',
    aliases: [
      'programming',
      'coding',
      'code',
      'developer',
      'development',
      'dev tools',
      'oss',
      'open source',
      'github',
      'backend',
      'frontend',
      'api',
    ],
    icons: [
      Icons.terminal_outlined,
      Icons.code_outlined,
      Icons.data_object_outlined,
      Icons.storage_outlined,
      Icons.cloud_outlined,
      Icons.account_tree_outlined,
      Icons.dns_outlined,
      Icons.memory_outlined,
      Icons.bug_report_outlined,
      Icons.api_outlined,
      Icons.schema_outlined,
      Icons.developer_board_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'artificial-intelligence',
    aliases: [
      'artificial intelligence',
      'ai',
      'ai agent',
      'machine learning',
      'neural network',
      'llm',
      'gpt',
      'prompt',
      'automation',
      'model',
    ],
    icons: [
      Icons.hub_outlined,
      Icons.psychology_outlined,
      Icons.memory_outlined,
      Icons.auto_awesome_outlined,
      Icons.account_tree_outlined,
      Icons.schema_outlined,
      Icons.model_training_outlined,
      Icons.smart_toy_outlined,
      Icons.device_hub_outlined,
      Icons.polyline_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'technology-gadgets',
    aliases: [
      'technology',
      'tech',
      'gadget',
      'gadgets',
      'gizmo',
      'hardware',
      'device',
      'devices',
      'smartphone',
      'computer',
      'wearable',
    ],
    icons: [
      Icons.laptop_outlined,
      Icons.smartphone_outlined,
      Icons.tablet_mac_outlined,
      Icons.memory_outlined,
      Icons.router_outlined,
      Icons.wifi_outlined,
      Icons.usb_outlined,
      Icons.keyboard_outlined,
      Icons.cloud_outlined,
      Icons.devices_other_outlined,
      Icons.headphones_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'design',
    aliases: [
      'design',
      'design system',
      'graphic design',
      'ui design',
      'ux design',
      'typography',
      'figma',
      'visual design',
    ],
    icons: [
      Icons.palette_outlined,
      Icons.draw_outlined,
      Icons.grid_view_outlined,
      Icons.layers_outlined,
      Icons.straighten_outlined,
      Icons.crop_free_outlined,
      Icons.polyline_outlined,
      Icons.mouse_outlined,
      Icons.architecture_outlined,
      Icons.text_fields_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'photography',
    aliases: [
      'photography',
      'photo',
      'camera',
      'portrait',
      'landscape photography',
      'photo editing',
    ],
    icons: [
      Icons.photo_camera_outlined,
      Icons.camera_alt_outlined,
      Icons.filter_center_focus_outlined,
      Icons.photo_library_outlined,
      Icons.crop_outlined,
      Icons.flash_on_outlined,
      Icons.image_outlined,
      Icons.filter_outlined,
      Icons.landscape_outlined,
      Icons.camera_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'wildlife',
    aliases: [
      'wildlife',
      'animal',
      'animals',
      'bird',
      'birds',
      'butterfly',
      'forest life',
    ],
    icons: [
      Icons.pets_outlined,
      Icons.flutter_dash_outlined,
      Icons.park_outlined,
      Icons.eco_outlined,
      Icons.forest_outlined,
      Icons.terrain_outlined,
      Icons.water_outlined,
      Icons.cruelty_free_outlined,
      Icons.emoji_nature_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'nature-outdoors',
    aliases: [
      'nature',
      'outdoors',
      'trek',
      'trekking',
      'hike',
      'hiking',
      'trail',
      'mountain',
      'camping',
      'river',
    ],
    icons: [
      Icons.park_outlined,
      Icons.eco_outlined,
      Icons.local_florist_outlined,
      Icons.cloud_outlined,
      Icons.wb_sunny_outlined,
      Icons.nights_stay_outlined,
      Icons.water_outlined,
      Icons.terrain_outlined,
      Icons.grass_outlined,
      Icons.explore_outlined,
      Icons.hiking_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'gardening',
    aliases: [
      'gardening',
      'garden',
      'plants',
      'plant care',
      'farming',
      'agriculture',
      'compost',
    ],
    icons: [
      Icons.yard_outlined,
      Icons.water_drop_outlined,
      Icons.grass_outlined,
      Icons.local_florist_outlined,
      Icons.eco_outlined,
      Icons.compost_outlined,
      Icons.agriculture_outlined,
      Icons.park_outlined,
      Icons.spa_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'travel',
    aliases: [
      'travel',
      'trip',
      'vacation',
      'destination',
      'backpacking',
      'tourism',
      'passport',
      'hotel',
    ],
    icons: [
      Icons.flight_outlined,
      Icons.luggage_outlined,
      Icons.map_outlined,
      Icons.place_outlined,
      Icons.explore_outlined,
      Icons.train_outlined,
      Icons.directions_boat_outlined,
      Icons.photo_camera_outlined,
      Icons.hiking_outlined,
      Icons.travel_explore_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'finance',
    aliases: [
      'finance',
      'money',
      'investing',
      'investment',
      'stocks',
      'market',
      'crypto',
      'banking',
      'personal finance',
    ],
    icons: [
      Icons.paid_outlined,
      Icons.account_balance_wallet_outlined,
      Icons.show_chart_outlined,
      Icons.account_balance_outlined,
      Icons.currency_rupee_outlined,
      Icons.attach_money_outlined,
      Icons.savings_outlined,
      Icons.calculate_outlined,
      Icons.candlestick_chart_outlined,
      Icons.pie_chart_outline_rounded,
    ],
  ),
  PatternCategoryDefinition(
    id: 'business',
    aliases: [
      'business',
      'startup',
      'founder',
      'entrepreneur',
      'marketing',
      'growth',
      'sales',
      'office',
      'management',
    ],
    icons: [
      Icons.business_center_outlined,
      Icons.apartment_outlined,
      Icons.query_stats_outlined,
      Icons.groups_outlined,
      Icons.checklist_outlined,
      Icons.calendar_month_outlined,
      Icons.ads_click_outlined,
      Icons.trending_up_outlined,
      Icons.track_changes_outlined,
      Icons.work_outline_rounded,
    ],
  ),
  PatternCategoryDefinition(
    id: 'education',
    aliases: [
      'education',
      'learning',
      'study',
      'course',
      'school',
      'college',
      'student',
      'teaching',
    ],
    icons: [
      Icons.school_outlined,
      Icons.menu_book_outlined,
      Icons.edit_note_outlined,
      Icons.science_outlined,
      Icons.public_outlined,
      Icons.calculate_outlined,
      Icons.local_library_outlined,
      Icons.quiz_outlined,
      Icons.history_edu_outlined,
      Icons.lightbulb_outline,
    ],
  ),
  PatternCategoryDefinition(
    id: 'science',
    aliases: [
      'science',
      'research',
      'biology',
      'chemistry',
      'physics',
      'laboratory',
      'medicine',
      'molecule',
      'dna',
    ],
    icons: [
      Icons.science_outlined,
      Icons.biotech_outlined,
      Icons.functions_outlined,
      Icons.public_outlined,
      Icons.bubble_chart_outlined,
      Icons.hub_outlined,
      Icons.polyline_outlined,
      Icons.scatter_plot_outlined,
      Icons.medical_information_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'astronomy-space',
    aliases: [
      'astronomy',
      'space',
      'planet',
      'galaxy',
      'satellite',
      'telescope',
      'rocket',
      'cosmos',
    ],
    icons: [
      Icons.public_outlined,
      Icons.rocket_launch_outlined,
      Icons.satellite_alt_outlined,
      Icons.nights_stay_outlined,
      Icons.star_outline_rounded,
      Icons.brightness_2_outlined,
      Icons.explore_outlined,
      Icons.language_outlined,
      Icons.auto_awesome_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'music',
    aliases: [
      'music',
      'song',
      'songs',
      'playlist',
      'album',
      'guitar',
      'piano',
      'audio',
    ],
    icons: [
      Icons.headphones_outlined,
      Icons.music_note_outlined,
      Icons.album_outlined,
      Icons.mic_none_outlined,
      Icons.speaker_outlined,
      Icons.graphic_eq_outlined,
      Icons.piano_outlined,
      Icons.queue_music_outlined,
      Icons.radio_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'podcasts',
    aliases: [
      'podcast',
      'podcasts',
      'audio show',
      'interview',
      'radio show',
      'spoken audio',
    ],
    icons: [
      Icons.mic_none_outlined,
      Icons.headphones_outlined,
      Icons.podcasts_outlined,
      Icons.graphic_eq_outlined,
      Icons.rss_feed_outlined,
      Icons.speaker_outlined,
      Icons.radio_outlined,
      Icons.hearing_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'gaming',
    aliases: [
      'gaming',
      'game',
      'games',
      'console',
      'esports',
      'video game',
      'pixel',
      'joystick',
    ],
    icons: [
      Icons.sports_esports_outlined,
      Icons.casino_outlined,
      Icons.extension_outlined,
      Icons.keyboard_outlined,
      Icons.computer_outlined,
      Icons.emoji_events_outlined,
      Icons.shield_outlined,
      Icons.bolt_outlined,
      Icons.token_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'sports',
    aliases: [
      'sports',
      'athlete',
      'athletics',
      'stadium',
      'competition',
      'tournament',
    ],
    icons: [
      Icons.sports_soccer_outlined,
      Icons.sports_basketball_outlined,
      Icons.sports_tennis_outlined,
      Icons.sports_cricket_outlined,
      Icons.emoji_events_outlined,
      Icons.timer_outlined,
      Icons.stadium_outlined,
      Icons.directions_run_outlined,
      Icons.scoreboard_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'cricket',
    aliases: ['cricket', 'ipl', 'test cricket', 't20', 'cricket match'],
    icons: [
      Icons.sports_cricket_outlined,
      Icons.sports_baseball_outlined,
      Icons.scoreboard_outlined,
      Icons.stadium_outlined,
      Icons.emoji_events_outlined,
      Icons.timer_outlined,
      Icons.sports_outlined,
      Icons.shield_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'football',
    aliases: ['football', 'soccer', 'premier league', 'fifa', 'football match'],
    icons: [
      Icons.sports_soccer_outlined,
      Icons.sports_football_outlined,
      Icons.stadium_outlined,
      Icons.scoreboard_outlined,
      Icons.directions_run_outlined,
      Icons.sports_outlined,
      Icons.emoji_events_outlined,
      Icons.flag_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'motorsport',
    aliases: [
      'motorsport',
      'formula 1',
      'f1',
      'racing',
      'race car',
      'grand prix',
    ],
    icons: [
      Icons.sports_motorsports_outlined,
      Icons.flag_outlined,
      Icons.speed_outlined,
      Icons.tire_repair_outlined,
      Icons.build_outlined,
      Icons.route_outlined,
      Icons.local_gas_station_outlined,
      Icons.engineering_outlined,
      Icons.timer_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'cycling',
    aliases: ['cycling', 'bike', 'bicycle', 'road cycling', 'mountain biking'],
    icons: [
      Icons.directions_bike_outlined,
      Icons.pedal_bike_outlined,
      Icons.two_wheeler_outlined,
      Icons.route_outlined,
      Icons.terrain_outlined,
      Icons.speed_outlined,
      Icons.health_and_safety_outlined,
      Icons.build_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'fashion',
    aliases: [
      'fashion',
      'clothing',
      'outfit',
      'streetwear',
      'style',
      'accessories',
    ],
    icons: [
      Icons.checkroom_outlined,
      Icons.style_outlined,
      Icons.shopping_bag_outlined,
      Icons.watch_outlined,
      Icons.content_cut_outlined,
      Icons.texture_outlined,
      Icons.diamond_outlined,
      Icons.dry_cleaning_outlined,
      Icons.local_mall_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'beauty',
    aliases: [
      'beauty',
      'skincare',
      'makeup',
      'cosmetics',
      'hair care',
      'perfume',
    ],
    icons: [
      Icons.face_retouching_natural_outlined,
      Icons.brush_outlined,
      Icons.spa_outlined,
      Icons.local_florist_outlined,
      Icons.colorize_outlined,
      Icons.water_drop_outlined,
      Icons.auto_awesome_outlined,
      Icons.health_and_safety_outlined,
      Icons.soap_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'pets',
    aliases: ['pets', 'pet care', 'dog', 'dogs', 'cat', 'cats', 'aquarium'],
    icons: [
      Icons.pets_outlined,
      Icons.cruelty_free_outlined,
      Icons.house_siding_outlined,
      Icons.water_drop_outlined,
      Icons.set_meal_outlined,
      Icons.flutter_dash_outlined,
      Icons.favorite_border_rounded,
      Icons.home_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'home-interiors',
    aliases: [
      'home',
      'interior',
      'interiors',
      'home decor',
      'furniture',
      'house',
      'kitchen design',
    ],
    icons: [
      Icons.home_work_outlined,
      Icons.chair_outlined,
      Icons.light_outlined,
      Icons.local_florist_outlined,
      Icons.kitchen_outlined,
      Icons.window_outlined,
      Icons.weekend_outlined,
      Icons.table_restaurant_outlined,
      Icons.door_front_door_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'diy-tools',
    aliases: [
      'diy',
      'tools',
      'woodworking',
      'home improvement',
      'repair',
      'craft',
      'maker',
    ],
    icons: [
      Icons.hardware_outlined,
      Icons.handyman_outlined,
      Icons.construction_outlined,
      Icons.build_outlined,
      Icons.home_repair_service_outlined,
      Icons.format_paint_outlined,
      Icons.architecture_outlined,
      Icons.square_foot_outlined,
      Icons.carpenter_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'automotive',
    aliases: [
      'automotive',
      'car',
      'cars',
      'vehicle',
      'vehicles',
      'auto repair',
    ],
    icons: [
      Icons.directions_car_outlined,
      Icons.tire_repair_outlined,
      Icons.settings_outlined,
      Icons.battery_charging_full_outlined,
      Icons.local_gas_station_outlined,
      Icons.route_outlined,
      Icons.speed_outlined,
      Icons.car_repair_outlined,
      Icons.minor_crash_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'motorcycles',
    aliases: [
      'motorcycle',
      'motorcycles',
      'motorbike',
      'bike touring',
      'rider',
    ],
    icons: [
      Icons.two_wheeler_outlined,
      Icons.sports_motorsports_outlined,
      Icons.route_outlined,
      Icons.build_outlined,
      Icons.shield_outlined,
      Icons.speed_outlined,
      Icons.health_and_safety_outlined,
      Icons.local_gas_station_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'productivity',
    aliases: [
      'productivity',
      'task management',
      'planning',
      'organizing',
      'calendar',
      'focus',
      'workflow',
    ],
    icons: [
      Icons.checklist_outlined,
      Icons.calendar_month_outlined,
      Icons.assignment_turned_in_outlined,
      Icons.timer_outlined,
      Icons.center_focus_strong_outlined,
      Icons.track_changes_outlined,
      Icons.folder_open_outlined,
      Icons.task_alt_outlined,
      Icons.event_note_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'minimalism',
    aliases: [
      'minimalism',
      'minimal',
      'simplicity',
      'simple living',
      'geometry',
    ],
    icons: [
      Icons.circle_outlined,
      Icons.crop_square_outlined,
      Icons.change_history_outlined,
      Icons.grid_4x4_outlined,
      Icons.balance_outlined,
      Icons.radio_button_unchecked_outlined,
      Icons.hexagon_outlined,
      Icons.horizontal_rule_outlined,
      Icons.all_out_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'philosophy',
    aliases: [
      'philosophy',
      'ethics',
      'stoicism',
      'existentialism',
      'wisdom',
      'meaning',
    ],
    icons: [
      Icons.account_balance_outlined,
      Icons.menu_book_outlined,
      Icons.balance_outlined,
      Icons.hourglass_empty_outlined,
      Icons.explore_outlined,
      Icons.lightbulb_outline,
      Icons.psychology_alt_outlined,
      Icons.temple_buddhist_outlined,
      Icons.history_edu_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'psychology',
    aliases: [
      'psychology',
      'mind',
      'mental model',
      'behavior',
      'cognition',
      'therapy',
    ],
    icons: [
      Icons.psychology_outlined,
      Icons.chat_bubble_outline_rounded,
      Icons.extension_outlined,
      Icons.account_tree_outlined,
      Icons.favorite_border_rounded,
      Icons.hub_outlined,
      Icons.self_improvement_outlined,
      Icons.lightbulb_outline,
      Icons.schema_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'history',
    aliases: [
      'history',
      'ancient history',
      'archaeology',
      'historical',
      'civilization',
      'artifact',
    ],
    icons: [
      Icons.history_edu_outlined,
      Icons.account_balance_outlined,
      Icons.castle_outlined,
      Icons.map_outlined,
      Icons.hourglass_empty_outlined,
      Icons.museum_outlined,
      Icons.public_outlined,
      Icons.receipt_long_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'languages',
    aliases: [
      'language',
      'languages',
      'language learning',
      'translation',
      'vocabulary',
      'grammar',
      'dictionary',
    ],
    icons: [
      Icons.chat_bubble_outline_rounded,
      Icons.public_outlined,
      Icons.translate_outlined,
      Icons.menu_book_outlined,
      Icons.abc_outlined,
      Icons.text_fields_outlined,
      Icons.record_voice_over_outlined,
      Icons.language_outlined,
      Icons.spellcheck_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'news',
    aliases: [
      'news',
      'current affairs',
      'journalism',
      'headlines',
      'world news',
      'breaking news',
    ],
    icons: [
      Icons.newspaper_outlined,
      Icons.campaign_outlined,
      Icons.public_outlined,
      Icons.notifications_none_outlined,
      Icons.rss_feed_outlined,
      Icons.article_outlined,
      Icons.radio_outlined,
      Icons.cell_tower_outlined,
      Icons.feed_outlined,
    ],
  ),
  PatternCategoryDefinition(
    id: 'sustainability',
    aliases: [
      'sustainability',
      'sustainable',
      'climate',
      'renewable energy',
      'green living',
      'environment',
      'recycling',
    ],
    icons: [
      Icons.recycling_outlined,
      Icons.eco_outlined,
      Icons.public_outlined,
      Icons.solar_power_outlined,
      Icons.wind_power_outlined,
      Icons.water_drop_outlined,
      Icons.park_outlined,
      Icons.compost_outlined,
      Icons.energy_savings_leaf_outlined,
    ],
  ),
];

const abstractPatternIcons = <IconData>[
  Icons.circle_outlined,
  Icons.crop_square_outlined,
  Icons.change_history_outlined,
  Icons.hexagon_outlined,
  Icons.adjust_outlined,
  Icons.all_out_outlined,
  Icons.scatter_plot_outlined,
  Icons.grid_4x4_outlined,
  Icons.radio_button_unchecked_outlined,
  Icons.polyline_outlined,
];
