enum PatternGrammar {
  circuitGrid,
  dataGraph,
  topographicMesh,
  waveform,
  synthwave,
  orbital,
  kineticTrack,
  editorialGrid,
  concentricGeometry,
  apertureFrames,
  ribbonMesh,
  contourRings,
  architecturalBlueprint,
  organicCells,
  sparseGeometry,
}

enum PatternComposition {
  fullBleed,
  cornerFocus,
  diagonalFlow,
  horizon,
  centralFocus,
  edgeWeighted,
}

class PatternRecipe {
  const PatternRecipe({
    required this.grammar,
    required this.composition,
    this.density = 0.5,
    this.scale = 1,
  }) : assert(density >= 0 && density <= 1),
       assert(scale > 0);

  final PatternGrammar grammar;
  final PatternComposition composition;
  final double density;
  final double scale;

  String get signature => '${grammar.name}:${composition.name}:$density:$scale';
}

class PatternCategoryDefinition {
  const PatternCategoryDefinition({
    required this.id,
    required this.aliases,
    required this.recipe,
  });

  final String id;
  final List<String> aliases;
  final PatternRecipe recipe;
}

const abstractPatternRecipe = PatternRecipe(
  grammar: PatternGrammar.sparseGeometry,
  composition: PatternComposition.diagonalFlow,
  density: 0.42,
  scale: 1,
);

const clusterPatternLibrary = <PatternCategoryDefinition>[
  PatternCategoryDefinition(
    id: 'food-nutrition',
    aliases: [
      'food',
      'nutrition',
      'healthy eating',
      'diet',
      'fruit',
      'vegetable',
      'grain',
      'herbs',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.contourRings,
      composition: PatternComposition.centralFocus,
      density: 0.62,
      scale: 1.05,
    ),
  ),
  PatternCategoryDefinition(
    id: 'cooking-recipes',
    aliases: [
      'cooking',
      'recipe',
      'recipes',
      'chef',
      'baking',
      'kitchen',
      'ingredients',
      'meal prep',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.contourRings,
      composition: PatternComposition.cornerFocus,
      density: 0.7,
      scale: 0.9,
    ),
  ),
  PatternCategoryDefinition(
    id: 'fitness',
    aliases: [
      'fitness',
      'workout',
      'exercise',
      'running',
      'gym',
      'strength',
      'activity',
      'training',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.kineticTrack,
      composition: PatternComposition.diagonalFlow,
      density: 0.72,
      scale: 1.05,
    ),
  ),
  PatternCategoryDefinition(
    id: 'wellness',
    aliases: [
      'wellness',
      'health',
      'meditation',
      'mindfulness',
      'sleep',
      'spa',
      'breathing',
      'self care',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.concentricGeometry,
      composition: PatternComposition.centralFocus,
      density: 0.44,
      scale: 1.15,
    ),
  ),
  PatternCategoryDefinition(
    id: 'movies',
    aliases: [
      'movie',
      'movies',
      'film',
      'cinema',
      'thriller',
      'director',
      'screening',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.synthwave,
      composition: PatternComposition.horizon,
      density: 0.62,
      scale: 1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'tv-shows',
    aliases: [
      'tv',
      'tv show',
      'television',
      'series',
      'episode',
      'streaming',
      'sitcom',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.synthwave,
      composition: PatternComposition.edgeWeighted,
      density: 0.52,
      scale: 0.92,
    ),
  ),
  PatternCategoryDefinition(
    id: 'anime-comics',
    aliases: [
      'anime',
      'manga',
      'comic',
      'comics',
      'graphic novel',
      'animation',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.synthwave,
      composition: PatternComposition.diagonalFlow,
      density: 0.76,
      scale: 0.86,
    ),
  ),
  PatternCategoryDefinition(
    id: 'books-reading',
    aliases: [
      'book',
      'books',
      'reading',
      'library',
      'novel',
      'literature',
      'essay',
      'poetry',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.editorialGrid,
      composition: PatternComposition.fullBleed,
      density: 0.48,
      scale: 1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'writing',
    aliases: [
      'writing',
      'writer',
      'journal',
      'journaling',
      'copywriting',
      'notes',
      'notebook',
      'typewriter',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.editorialGrid,
      composition: PatternComposition.cornerFocus,
      density: 0.56,
      scale: 0.92,
    ),
  ),
  PatternCategoryDefinition(
    id: 'programming',
    aliases: [
      'programming',
      'coding',
      'code',
      'developer',
      'development',
      'dev tools',
      'oss',
      'open source',
      'github',
      'backend',
      'frontend',
      'api',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.circuitGrid,
      composition: PatternComposition.fullBleed,
      density: 0.66,
      scale: 0.9,
    ),
  ),
  PatternCategoryDefinition(
    id: 'artificial-intelligence',
    aliases: [
      'artificial intelligence',
      'ai',
      'ai agent',
      'machine learning',
      'neural network',
      'llm',
      'gpt',
      'prompt',
      'automation',
      'model',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.circuitGrid,
      composition: PatternComposition.centralFocus,
      density: 0.78,
      scale: 1.08,
    ),
  ),
  PatternCategoryDefinition(
    id: 'technology-gadgets',
    aliases: [
      'technology',
      'tech',
      'gadget',
      'gadgets',
      'gizmo',
      'hardware',
      'device',
      'devices',
      'smartphone',
      'computer',
      'wearable',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.circuitGrid,
      composition: PatternComposition.diagonalFlow,
      density: 0.58,
      scale: 1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'design',
    aliases: [
      'design',
      'design system',
      'graphic design',
      'ui design',
      'ux design',
      'typography',
      'figma',
      'visual design',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.apertureFrames,
      composition: PatternComposition.edgeWeighted,
      density: 0.5,
      scale: 1.08,
    ),
  ),
  PatternCategoryDefinition(
    id: 'photography',
    aliases: [
      'photography',
      'photo',
      'camera',
      'portrait',
      'landscape photography',
      'photo editing',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.apertureFrames,
      composition: PatternComposition.centralFocus,
      density: 0.58,
      scale: 1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'wildlife',
    aliases: [
      'wildlife',
      'animal',
      'animals',
      'bird',
      'birds',
      'butterfly',
      'forest life',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.topographicMesh,
      composition: PatternComposition.fullBleed,
      density: 0.64,
      scale: 0.82,
    ),
  ),
  PatternCategoryDefinition(
    id: 'nature-outdoors',
    aliases: [
      'nature',
      'outdoors',
      'trek',
      'trekking',
      'hike',
      'hiking',
      'trail',
      'mountain',
      'camping',
      'river',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.topographicMesh,
      composition: PatternComposition.diagonalFlow,
      density: 0.58,
      scale: 1.08,
    ),
  ),
  PatternCategoryDefinition(
    id: 'gardening',
    aliases: [
      'gardening',
      'garden',
      'plants',
      'plant care',
      'farming',
      'agriculture',
      'compost',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.topographicMesh,
      composition: PatternComposition.cornerFocus,
      density: 0.72,
      scale: 0.78,
    ),
  ),
  PatternCategoryDefinition(
    id: 'travel',
    aliases: [
      'travel',
      'trip',
      'vacation',
      'destination',
      'backpacking',
      'tourism',
      'passport',
      'hotel',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.topographicMesh,
      composition: PatternComposition.horizon,
      density: 0.5,
      scale: 1.18,
    ),
  ),
  PatternCategoryDefinition(
    id: 'finance',
    aliases: [
      'finance',
      'money',
      'investing',
      'investment',
      'stocks',
      'market',
      'crypto',
      'banking',
      'personal finance',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.dataGraph,
      composition: PatternComposition.diagonalFlow,
      density: 0.7,
      scale: 1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'business',
    aliases: [
      'business',
      'startup',
      'founder',
      'entrepreneur',
      'marketing',
      'growth',
      'sales',
      'office',
      'management',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.dataGraph,
      composition: PatternComposition.edgeWeighted,
      density: 0.56,
      scale: 1.1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'education',
    aliases: [
      'education',
      'learning',
      'study',
      'course',
      'school',
      'college',
      'student',
      'teaching',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.orbital,
      composition: PatternComposition.edgeWeighted,
      density: 0.48,
      scale: 0.92,
    ),
  ),
  PatternCategoryDefinition(
    id: 'science',
    aliases: [
      'science',
      'research',
      'biology',
      'chemistry',
      'physics',
      'laboratory',
      'medicine',
      'molecule',
      'dna',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.orbital,
      composition: PatternComposition.fullBleed,
      density: 0.68,
      scale: 0.86,
    ),
  ),
  PatternCategoryDefinition(
    id: 'astronomy-space',
    aliases: [
      'astronomy',
      'space',
      'planet',
      'galaxy',
      'satellite',
      'telescope',
      'rocket',
      'cosmos',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.orbital,
      composition: PatternComposition.centralFocus,
      density: 0.6,
      scale: 1.2,
    ),
  ),
  PatternCategoryDefinition(
    id: 'music',
    aliases: [
      'music',
      'song',
      'songs',
      'playlist',
      'album',
      'guitar',
      'piano',
      'audio',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.waveform,
      composition: PatternComposition.fullBleed,
      density: 0.68,
      scale: 1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'podcasts',
    aliases: [
      'podcast',
      'podcasts',
      'audio show',
      'interview',
      'radio show',
      'spoken audio',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.waveform,
      composition: PatternComposition.edgeWeighted,
      density: 0.5,
      scale: 0.88,
    ),
  ),
  PatternCategoryDefinition(
    id: 'gaming',
    aliases: [
      'gaming',
      'game',
      'games',
      'console',
      'esports',
      'video game',
      'pixel',
      'joystick',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.synthwave,
      composition: PatternComposition.centralFocus,
      density: 0.76,
      scale: 1.05,
    ),
  ),
  PatternCategoryDefinition(
    id: 'sports',
    aliases: [
      'sports',
      'athlete',
      'athletics',
      'stadium',
      'competition',
      'tournament',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.kineticTrack,
      composition: PatternComposition.fullBleed,
      density: 0.58,
      scale: 1.08,
    ),
  ),
  PatternCategoryDefinition(
    id: 'cricket',
    aliases: ['cricket', 'ipl', 'test cricket', 't20', 'cricket match'],
    recipe: PatternRecipe(
      grammar: PatternGrammar.kineticTrack,
      composition: PatternComposition.cornerFocus,
      density: 0.52,
      scale: 0.96,
    ),
  ),
  PatternCategoryDefinition(
    id: 'football',
    aliases: ['football', 'soccer', 'premier league', 'fifa', 'football match'],
    recipe: PatternRecipe(
      grammar: PatternGrammar.kineticTrack,
      composition: PatternComposition.diagonalFlow,
      density: 0.66,
      scale: 0.9,
    ),
  ),
  PatternCategoryDefinition(
    id: 'motorsport',
    aliases: [
      'motorsport',
      'formula 1',
      'f1',
      'racing',
      'race car',
      'grand prix',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.kineticTrack,
      composition: PatternComposition.horizon,
      density: 0.76,
      scale: 1.15,
    ),
  ),
  PatternCategoryDefinition(
    id: 'cycling',
    aliases: ['cycling', 'bike', 'bicycle', 'road cycling', 'mountain biking'],
    recipe: PatternRecipe(
      grammar: PatternGrammar.kineticTrack,
      composition: PatternComposition.edgeWeighted,
      density: 0.48,
      scale: 0.88,
    ),
  ),
  PatternCategoryDefinition(
    id: 'fashion',
    aliases: [
      'fashion',
      'clothing',
      'outfit',
      'streetwear',
      'style',
      'accessories',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.ribbonMesh,
      composition: PatternComposition.diagonalFlow,
      density: 0.58,
      scale: 1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'beauty',
    aliases: [
      'beauty',
      'skincare',
      'makeup',
      'cosmetics',
      'hair care',
      'perfume',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.ribbonMesh,
      composition: PatternComposition.cornerFocus,
      density: 0.48,
      scale: 1.12,
    ),
  ),
  PatternCategoryDefinition(
    id: 'pets',
    aliases: ['pets', 'pet care', 'dog', 'dogs', 'cat', 'cats', 'aquarium'],
    recipe: PatternRecipe(
      grammar: PatternGrammar.organicCells,
      composition: PatternComposition.fullBleed,
      density: 0.6,
      scale: 1,
    ),
  ),
  PatternCategoryDefinition(
    id: 'home-interiors',
    aliases: [
      'home',
      'interior',
      'interiors',
      'home decor',
      'furniture',
      'house',
      'kitchen design',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.architecturalBlueprint,
      composition: PatternComposition.edgeWeighted,
      density: 0.52,
      scale: 1.08,
    ),
  ),
  PatternCategoryDefinition(
    id: 'diy-tools',
    aliases: [
      'diy',
      'tools',
      'woodworking',
      'home improvement',
      'repair',
      'craft',
      'maker',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.architecturalBlueprint,
      composition: PatternComposition.fullBleed,
      density: 0.7,
      scale: 0.9,
    ),
  ),
  PatternCategoryDefinition(
    id: 'automotive',
    aliases: [
      'automotive',
      'car',
      'cars',
      'vehicle',
      'vehicles',
      'auto repair',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.kineticTrack,
      composition: PatternComposition.horizon,
      density: 0.6,
      scale: 1.08,
    ),
  ),
  PatternCategoryDefinition(
    id: 'motorcycles',
    aliases: [
      'motorcycle',
      'motorcycles',
      'motorbike',
      'bike touring',
      'rider',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.kineticTrack,
      composition: PatternComposition.diagonalFlow,
      density: 0.7,
      scale: 0.96,
    ),
  ),
  PatternCategoryDefinition(
    id: 'productivity',
    aliases: [
      'productivity',
      'task management',
      'planning',
      'organizing',
      'calendar',
      'focus',
      'workflow',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.circuitGrid,
      composition: PatternComposition.edgeWeighted,
      density: 0.46,
      scale: 1.12,
    ),
  ),
  PatternCategoryDefinition(
    id: 'minimalism',
    aliases: [
      'minimalism',
      'minimal',
      'simplicity',
      'simple living',
      'geometry',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.sparseGeometry,
      composition: PatternComposition.centralFocus,
      density: 0.2,
      scale: 1.2,
    ),
  ),
  PatternCategoryDefinition(
    id: 'philosophy',
    aliases: [
      'philosophy',
      'ethics',
      'stoicism',
      'existentialism',
      'wisdom',
      'meaning',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.concentricGeometry,
      composition: PatternComposition.centralFocus,
      density: 0.52,
      scale: 1.12,
    ),
  ),
  PatternCategoryDefinition(
    id: 'psychology',
    aliases: [
      'psychology',
      'mind',
      'mental model',
      'behavior',
      'cognition',
      'therapy',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.concentricGeometry,
      composition: PatternComposition.diagonalFlow,
      density: 0.64,
      scale: 0.92,
    ),
  ),
  PatternCategoryDefinition(
    id: 'history',
    aliases: [
      'history',
      'ancient history',
      'archaeology',
      'historical',
      'civilization',
      'artifact',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.editorialGrid,
      composition: PatternComposition.edgeWeighted,
      density: 0.58,
      scale: 1.08,
    ),
  ),
  PatternCategoryDefinition(
    id: 'languages',
    aliases: [
      'language',
      'languages',
      'language learning',
      'translation',
      'vocabulary',
      'grammar',
      'dictionary',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.editorialGrid,
      composition: PatternComposition.diagonalFlow,
      density: 0.62,
      scale: 0.88,
    ),
  ),
  PatternCategoryDefinition(
    id: 'news',
    aliases: [
      'news',
      'current affairs',
      'journalism',
      'headlines',
      'world news',
      'breaking news',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.dataGraph,
      composition: PatternComposition.fullBleed,
      density: 0.66,
      scale: 0.92,
    ),
  ),
  PatternCategoryDefinition(
    id: 'sustainability',
    aliases: [
      'sustainability',
      'sustainable',
      'climate',
      'renewable energy',
      'green living',
      'environment',
      'recycling',
    ],
    recipe: PatternRecipe(
      grammar: PatternGrammar.topographicMesh,
      composition: PatternComposition.edgeWeighted,
      density: 0.54,
      scale: 1,
    ),
  ),
];
